// generated by Neptune Namespaces v4.x.x
// file: Art/Engine/File/index.js

(module.exports = require('./namespace'))

.addModules({
  StandardImport:   require('./StandardImport'),
  V1CompositeModes: require('./V1CompositeModes'),
  V1LayoutModes:    require('./V1LayoutModes'),
  V1Loader:         require('./V1Loader'),
  V1Writer:         require('./V1Writer')
});