# generated by Neptune Namespaces v3.x.x
# file: Art/Engine/File/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  V1Loader: require './V1Loader'
  V1Writer: require './V1Writer'