# generated by Neptune Namespaces v1.x.x
# file: Art/Engine/File/namespace.coffee

Engine = require '../namespace'
module.exports = Engine.File ||
Engine.addNamespace 'File', class File extends Neptune.Base
  ;