# generated by Neptune Namespaces
# file: tests/art/engine/file/index.coffee

module.exports =
File          = require './namespace'
File.V1Writer = require './v1_writer'
File.finishLoad(
  ["V1Writer"]
)