# generated by Neptune Namespaces v2.x.x
# file: tests/Art/Engine/File/namespace.coffee

Engine = require '../namespace'
module.exports = Engine.File ||
Engine.addNamespace 'File', class File extends Neptune.Base
  ;
