# generated by Neptune Namespaces
# file: tests/art/engine/file/namespace.coffee

Engine = require '../namespace'
module.exports = Engine.File ||
Engine.addNamespace class File extends Neptune.Base
  ;