# generated by Neptune Namespaces v0.3.0
# file: tests/art/engine/file/namespace.coffee

Engine = require '../namespace'
module.exports = Engine.File ||
Engine.addNamespace 'File', class File extends Neptune.Base
  ;