# generated by Neptune Namespaces v0.3.0
# file: tests/art/engine/elements/shapes/index.coffee

(module.exports = require './namespace')
.addModules
  BitmapElement:    require './bitmap_element'
  RectangleElement: require './rectangle_element'
  TextElement:      require './text_element'