# generated by Neptune Namespaces v1.x.x
# file: tests/Art/Engine/Elements/Shapes/index.coffee

module.exports = require './namespace'
.addModules
  BitmapElement:    require './BitmapElement'    
  RectangleElement: require './rectangle_element'
  TextElement:      require './TextElement'      