# generated by Neptune Namespaces v2.x.x
# file: tests/Art/Engine/Elements/Shapes/namespace.coffee

Elements = require '../namespace'
module.exports = Elements.Shapes ||
Elements.addNamespace 'Shapes', class Shapes extends Neptune.Base
  ;
