# generated by Neptune Namespaces
# file: tests/art/engine/elements/shapes/namespace.coffee

Elements = require '../namespace'
module.exports = Elements.Shapes ||
Elements.addNamespace class Shapes extends Neptune.Base
  ;