# generated by Neptune Namespaces v0.4.1
# file: tests/art/engine/elements/shapes/namespace.coffee

Elements = require '../namespace'
module.exports = Elements.Shapes ||
Elements.addNamespace 'Shapes', class Shapes extends Neptune.Base
  ;