# generated by Neptune Namespaces
# file: tests/art/engine/elements/shapes/namespace.coffee

Elements = require '../namespace'
module.exports = Elements.Shapes ||
class Elements.Shapes extends Neptune.Base
  @namespace: Elements
  @namespacePath: "Neptune.Tests.Art.Engine.Elements.Shapes"

Elements.addNamespace Elements.Shapes