# generated by Neptune Namespaces v1.x.x
# file: tests/Art/Engine/Core/Drawing/index.coffee

module.exports = require './namespace'
.addModules
  Basics:        require './Basics'       
  PartialRedraw: require './PartialRedraw'
  Retina:        require './Retina'       
  ToBitmap:      require './toBitmap'     