# generated by Neptune Namespaces v1.x.x
# file: tests/Art/Engine/Core/Drawing/namespace.coffee

Core = require '../namespace'
module.exports = Core.Drawing ||
Core.addNamespace 'Drawing', class Drawing extends Neptune.Base
  ;