// generated by Neptune Namespaces v4.x.x
// file: Art/Engine/Elements/Shapes/index.js

(module.exports = require('./namespace'))

.addModules({
  BitmapElement:    require('./BitmapElement'),
  RectangleElement: require('./RectangleElement'),
  ShapeElement:     require('./ShapeElement'),
  TextElement:      require('./TextElement')
});