# generated by Neptune Namespaces v3.x.x
# file: Art/Engine/Elements/Shapes/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  BitmapElement:    require './BitmapElement'   
  RectangleElement: require './RectangleElement'
  ShapeElement:     require './ShapeElement'    
  TextElement:      require './TextElement'     