# generated by Neptune Namespaces v1.x.x
# file: Art/Engine/Elements/Shapes/namespace.coffee

Elements = require '../namespace'
module.exports = Elements.Shapes ||
Elements.addNamespace 'Shapes', class Shapes extends Neptune.Base
  ;