// generated by Neptune Namespaces v4.x.x
// file: Art/Engine/Elements/Shapes/namespace.js

module.exports = require('../namespace').addNamespace(
  'Shapes',
  class Shapes extends Neptune.PackageNamespace {}
);
