# generated by Neptune Namespaces v1.x.x
# file: Art/Engine/Elements/Filters/index.coffee

module.exports = require './namespace'
.addModules
  BlurElement:   require './BlurElement'  
  FilterElement: require './FilterElement'
  ShadowElement: require './ShadowElement'