// generated by Neptune Namespaces v4.x.x
// file: Art/Engine/Elements/Filters/index.js

(module.exports = require('./namespace'))

.addModules({
  BlurElement:   require('./BlurElement'),
  FilterElement: require('./FilterElement'),
  ShadowElement: require('./ShadowElement')
});