# generated by Neptune Namespaces v1.x.x
# file: Art/Engine/Elements/Filters/namespace.coffee

Elements = require '../namespace'
module.exports = Elements.Filters ||
Elements.addNamespace 'Filters', class Filters extends Neptune.Base
  ;