# generated by Neptune Namespaces v3.x.x
# file: tests/Engine/Elements/Widgets/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  PagingScrollElement: require './PagingScrollElement'