# generated by Neptune Namespaces v0.1.0
# file: tests/art/engine/layout/index.coffee

(module.exports = require './namespace')
.addModules
  LinearLayout: require './linear_layout'
  PointLayout:  require './point_layout'