# generated by Neptune Namespaces v0.1.0
# file: tests/art/engine/layout/namespace.coffee

Engine = require '../namespace'
module.exports = Engine.Layout ||
Engine.addNamespace class Layout extends Neptune.Base
  ;