# generated by Neptune Namespaces v2.x.x
# file: tests/Art/Engine/Layout/namespace.coffee

Engine = require '../namespace'
module.exports = Engine.Layout ||
Engine.addNamespace 'Layout', class Layout extends Neptune.Base
  ;
