# generated by Neptune Namespaces v0.4.1
# file: tests/art/engine/layout/namespace.coffee

Engine = require '../namespace'
module.exports = Engine.Layout ||
Engine.addNamespace 'Layout', class Layout extends Neptune.Base
  ;