# generated by Neptune Namespaces v1.x.x
# file: Art/Engine/Animation/index.coffee

module.exports = require './namespace'
.addModules
  Animator:                   require './Animator'                  
  EasingFunctions:            require './EasingFunctions'           
  EasingPersistantAnimator:   require './EasingPersistantAnimator'  
  PeriodicPersistantAnimator: require './PeriodicPersistantAnimator'
  PersistantAnimator:         require './PersistantAnimator'        