// generated by Neptune Namespaces v4.x.x
// file: Art/Engine/Animation/index.js

(module.exports = require('./namespace'))

.addModules({
  Animator:                   require('./Animator'),
  EasingFunctions:            require('./EasingFunctions'),
  EasingPersistantAnimator:   require('./EasingPersistantAnimator'),
  PeriodicPersistantAnimator: require('./PeriodicPersistantAnimator'),
  PersistantAnimator:         require('./PersistantAnimator')
});