# generated by Neptune Namespaces v3.x.x
# file: Art/Engine/Animation/namespace.coffee

module.exports = (require '../namespace').addNamespace('Animation', class Animation extends Neptune.PackageNamespace)
