// generated by Neptune Namespaces v4.x.x
// file: Art/Engine/Animation/namespace.js

module.exports = require('../namespace').addNamespace(
  'Animation',
  class Animation extends Neptune.PackageNamespace {}
);
