# generated by Neptune Namespaces v2.x.x
# file: Art/Engine/Animation/namespace.coffee

Engine = require '../namespace'
module.exports = Engine.Animation ||
Engine.addNamespace 'Animation', class Animation extends Neptune.Base
  ;
