# generated by Neptune Namespaces v3.x.x
# file: tests/Engine/namespace.coffee

module.exports = (require '../namespace').addNamespace 'Engine', class Engine extends Neptune.PackageNamespace
  @version: require('../../../package.json').version
require './Core/namespace';
require './Elements/namespace';
require './Events/namespace';
require './File/namespace';
require './Layout/namespace';
require './ZAnimation/namespace'