# generated by Neptune Namespaces v3.x.x
# file: Art/Engine/Events/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  GestureRecognizer:   require './GestureRecognizer'  
  KeyEvent:            require './KeyEvent'           
  MultitouchManager:   require './MultitouchManager'  
  Pointer:             require './Pointer'            
  PointerEvent:        require './PointerEvent'       
  PointerEventManager: require './PointerEventManager'