// generated by Neptune Namespaces v4.x.x
// file: Art/Engine/Events/index.js

(module.exports = require('./namespace'))

.addModules({
  GestureRecognizer:   require('./GestureRecognizer'),
  KeyEvent:            require('./KeyEvent'),
  MultitouchManager:   require('./MultitouchManager'),
  Pointer:             require('./Pointer'),
  PointerEvent:        require('./PointerEvent'),
  PointerEventManager: require('./PointerEventManager')
});