# generated by Neptune Namespaces v1.x.x
# file: Art/Engine/Events/index.coffee

module.exports = require './namespace'
.addModules
  GestureRecognizer:   require './GestureRecognizer'  
  KeyEvent:            require './KeyEvent'           
  Pointer:             require './Pointer'            
  PointerEvent:        require './PointerEvent'       
  PointerEventManager: require './PointerEventManager'