// generated by Neptune Namespaces v4.x.x
// file: Art/Engine/Events/namespace.js

module.exports = require('../namespace').addNamespace(
  'Events',
  class Events extends Neptune.PackageNamespace {}
);
