# generated by Neptune Namespaces v2.x.x
# file: Art/Engine/Events/namespace.coffee

Engine = require '../namespace'
module.exports = Engine.Events ||
Engine.addNamespace 'Events', class Events extends Neptune.Base
  ;
