// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Engine/namespace.js

module.exports = require('../namespace').addNamespace(
  'Art.Engine',
  class Engine extends Neptune.PackageNamespace {}
);
require('./Core/namespace');
require('./Elements/namespace');
require('./Events/namespace');
require('./File/namespace');
require('./Layout/namespace');
require('./ZAnimation/namespace');