# generated by Neptune Namespaces v1.x.x
# file: tests/Art/Engine/Elements/Widgets/index.coffee

module.exports = require './namespace'
.addModules
  PagingScrollElement: require './PagingScrollElement'