# generated by Neptune Namespaces v2.x.x
# file: tests/Art/Engine/Elements/Widgets/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  PagingScrollElement: require './PagingScrollElement'