# generated by Neptune Namespaces
# file: tests/art/engine/elements/widgets/index.coffee

(module.exports = require './namespace')
.addModules
  PagingScrollElement: require './paging_scroll_element'
