# generated by Neptune Namespaces
# file: tests/art/engine/elements/widgets/index.coffee

module.exports =
Widgets                     = require './namespace'
Widgets.PagingScrollElement = require './paging_scroll_element'
Widgets.finishLoad(
  ["PagingScrollElement"]
)