# generated by Neptune Namespaces v0.1.0
# file: tests/art/engine/elements/widgets/namespace.coffee

Elements = require '../namespace'
module.exports = Elements.Widgets ||
Elements.addNamespace class Widgets extends Neptune.Base
  ;