# generated by Neptune Namespaces v2.x.x
# file: tests/Art/Engine/Elements/Widgets/namespace.coffee

Elements = require '../namespace'
module.exports = Elements.Widgets ||
Elements.addNamespace 'Widgets', class Widgets extends Neptune.Base
  ;
