# generated by Neptune Namespaces v0.4.1
# file: art/engine/core/index.coffee

(module.exports = require './namespace')
.includeInNamespace(require './_core')
.addModules
  CanvasElement:        require './canvas_element'
  DrawCacheManager:     require './draw_cache_manager'
  DrawEpoch:            require './draw_epoch'
  Element:              require './element'
  ElementBase:          require './element_base'
  ElementFactory:       require './element_factory'
  EngineStat:           require './engine_stat'
  EpochedObject:        require './epoched_object'
  EventedEpochedObject: require './evented_epoched_object'
  GlobalEpochCycle:     require './global_epoch_cycle'
  IdleEpoch:            require './idle_epoch'
  StateEpoch:           require './state_epoch'
require './epoch_layout'