# generated by Neptune Namespaces
# file: art/engine/core/namespace.coffee

Engine = require '../namespace'
module.exports = Engine.Core ||
class Engine.Core extends Neptune.Base
  @namespace: Engine
  @namespacePath: "Neptune.Art.Engine.Core"

Engine.addNamespace Engine.Core