# generated by Neptune Namespaces v0.3.0
# file: art/engine/core/namespace.coffee

Engine = require '../namespace'
module.exports = Engine.Core ||
Engine.addNamespace 'Core', class Core extends Neptune.Base
  ;