# generated by Neptune Namespaces v0.1.0
# file: art/engine/core/namespace.coffee

Engine = require '../namespace'
module.exports = Engine.Core ||
Engine.addNamespace class Core extends Neptune.Base
  ;