# generated by Neptune Namespaces
# file: tests/art/engine/core/element/index.coffee

module.exports =
Element           = require './namespace'
Element.CacheDraw = require './cache_draw'
Element.Drawing   = require './drawing'
Element.finishLoad(
  ["CacheDraw","Drawing"]
)