# generated by Neptune Namespaces v0.1.0
# file: tests/art/engine/core/element/index.coffee

(module.exports = require './namespace')
.addModules
  Basics:    require './basics'
  CacheDraw: require './cache_draw'
  Drawing:   require './drawing'