# generated by Neptune Namespaces v1.x.x
# file: tests/Art/Engine/Core/Element/index.coffee

module.exports = require './namespace'
.addModules
  Basics:    require './Basics'   
  CacheDraw: require './CacheDraw'