# generated by Neptune Namespaces v0.5
# file: tests/art/engine/core/element/namespace.coffee

Core = require '../namespace'
module.exports = Core.Element ||
Core.addNamespace 'Element', class Element extends Neptune.Base
  ;