# generated by Neptune Namespaces
# file: tests/art/engine/core/element/namespace.coffee

Core = require '../namespace'
module.exports = Core.Element ||
class Core.Element extends Neptune.Base
  @namespace: Core
  @namespacePath: "Neptune.Tests.Art.Engine.Core.Element"

Core.addNamespace Core.Element