# generated by Neptune Namespaces v1.x.x
# file: tests/Art/Engine/Core/Element/namespace.coffee

Core = require '../namespace'
module.exports = Core.Element ||
Core.addNamespace 'Element', class Element extends Neptune.Base
  ;