# generated by Neptune Namespaces
# file: tests/art/engine/core/element/namespace.coffee

Core = require '../namespace'
module.exports = Core.Element ||
Core.addNamespace class Element extends Neptune.Base
  ;