# generated by Neptune Namespaces v3.x.x
# file: tests/Engine/Elements/Filters/namespace.coffee

module.exports = (require '../namespace').addNamespace('Filters', class Filters extends Neptune.PackageNamespace)
