# generated by Neptune Namespaces v3.x.x
# file: tests/Engine/Core/Layout/Functional/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Basics:           require './Basics'          
  ChildrenRelative: require './ChildrenRelative'
  ChildrenSize:     require './ChildrenSize'    
  Padding:          require './Padding'         
  Scale:            require './Scale'           