# generated by Neptune Namespaces v3.x.x
# file: tests/Engine/Core/Layout/Functional/namespace.coffee

module.exports = (require '../namespace').addNamespace('Functional', class Functional extends Neptune.PackageNamespace)
