# generated by Neptune Namespaces v0.3.0
# file: art/engine/core/epoch_layout/index.coffee

(module.exports = require './namespace')
.addModules
  Basics:           require './basics'
  FlexLayout:       require './flex_layout'
  StateEpochLayout: require './state_epoch_layout'