# generated by Neptune Namespaces
# file: art/engine/core/epoch_layout/index.coffee

module.exports =
EpochLayout                  = require './namespace'
EpochLayout.Basics           = require './basics'
EpochLayout.FlexLayout       = require './flex_layout'
EpochLayout.StateEpochLayout = require './state_epoch_layout'
EpochLayout.finishLoad(
  ["Basics","FlexLayout","StateEpochLayout"]
)