# generated by Neptune Namespaces v0.1.0
# file: art/engine/core/epoch_layout/namespace.coffee

Core = require '../namespace'
module.exports = Core.EpochLayout ||
Core.addNamespace class EpochLayout extends Neptune.Base
  ;