# generated by Neptune Namespaces v3.x.x
# file: tests/Art.Engine/Elements/Filters/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  BlurElement:   require './BlurElement'  
  FilterElement: require './FilterElement'
  ShadowElement: require './ShadowElement'