// generated by Neptune Namespaces v4.x.x
// file: Art/Engine/Layout/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./Layout'))
.addModules({
  InterpolatedPointLayout: require('./InterpolatedPointLayout'),
  PointLayout:             require('./PointLayout'),
  PointLayoutBase:         require('./PointLayoutBase')
});