// generated by Neptune Namespaces v4.x.x
// file: Art/Engine/Layout/namespace.js

module.exports = require('../namespace').addNamespace(
  'Layout',
  class Layout extends Neptune.PackageNamespace {}
);
