# generated by Neptune Namespaces
# this file: src/art/engine/elements/index.coffee

module.exports =
Elements                     = require './namespace'
Elements.Filters             = require './filters'
Elements.Shapes              = require './shapes'
Elements.All                 = require './all'
Elements.Base                = require './base'
Elements.Bitmap              = require './bitmap'
Elements.Fill                = require './fill'
Elements.FillableBase        = require './fillable_base'
Elements.Outline             = require './outline'
Elements.PagingScrollElement = require './paging_scroll_element'
Elements.RectangleShadow     = require './rectangle_shadow'
Elements.ScrollElement       = require './scroll_element'
Elements.TextElement         = require './text_element'
Elements.finishLoad(
  ["All","Base","Bitmap","Fill","FillableBase","Outline","PagingScrollElement","RectangleShadow","ScrollElement","TextElement"]
)