# generated by Neptune Namespaces
# file: art/engine/elements/index.coffee

(module.exports = require './namespace')
.addModules
  _All:          require './_all'
  Base:          require './base'
  FillableBase:  require './fillable_base'
require './filters'
require './shape_children'
require './shapes'
require './widgets'