# generated by Neptune Namespaces v0.5
# file: art/engine/elements/index.coffee

module.exports = require './namespace'
.includeInNamespace require './_elements'
.addModules
  Base:         require './base'         
  FillableBase: require './fillable_base'
require './filters'
require './shape_children'
require './shapes'
require './widgets'