# generated by Neptune Namespaces v0.4.1
# file: art/engine/elements/namespace.coffee

Engine = require '../namespace'
module.exports = Engine.Elements ||
Engine.addNamespace 'Elements', class Elements extends Neptune.Base
  ;