# generated by Neptune Namespaces
# file: src/art/engine/elements/namespace.coffee

Engine = require '../namespace'
module.exports = Engine.Elements ||
class Engine.Elements extends Neptune.Base
  @namespace: Engine
  @namespacePath: "Neptune.Art.Engine.Elements"

Engine.addNamespace Engine.Elements