# generated by Neptune Namespaces
# file: art/engine/elements/namespace.coffee

Engine = require '../namespace'
module.exports = Engine.Elements ||
Engine.addNamespace class Elements extends Neptune.Base
  ;