# generated by Neptune Namespaces
# file: art/engine/elements/shape_children/index.coffee

module.exports =
ShapeChildren         = require './namespace'
ShapeChildren.Fill    = require './fill'
ShapeChildren.Outline = require './outline'
ShapeChildren.finishLoad(
  ["Fill","Outline"]
)