# generated by Neptune Namespaces v1.x.x
# file: art/engine/elements/shape_children/index.coffee

module.exports = require './namespace'
.addModules
  FillElement:    require './fill_element'   
  OutlineElement: require './outline_element'