# generated by Neptune Namespaces
# file: art/engine/elements/shape_children/index.coffee

module.exports =
ShapeChildren                = require './namespace'
ShapeChildren.FillElement    = require './fill_element'
ShapeChildren.OutlineElement = require './outline_element'
ShapeChildren.finishLoad(
  ["FillElement","OutlineElement"]
)