# generated by Neptune Namespaces v0.5
# file: art/engine/elements/shape_children/namespace.coffee

Elements = require '../namespace'
module.exports = Elements.ShapeChildren ||
Elements.addNamespace 'ShapeChildren', class ShapeChildren extends Neptune.Base
  ;