# generated by Neptune Namespaces
# file: art/engine/elements/shape_children/namespace.coffee

Elements = require '../namespace'
module.exports = Elements.ShapeChildren ||
class Elements.ShapeChildren extends Neptune.Base
  @namespace: Elements
  @namespacePath: "Neptune.Art.Engine.Elements.ShapeChildren"

Elements.addNamespace Elements.ShapeChildren