# generated by Neptune Namespaces v0.1.0
# file: art/engine/elements/shape_children/namespace.coffee

Elements = require '../namespace'
module.exports = Elements.ShapeChildren ||
Elements.addNamespace class ShapeChildren extends Neptune.Base
  ;