# generated by Neptune Namespaces v0.1.0
# file: tests/art/engine/elements/index.coffee

(module.exports = require './namespace')
.addModules
  Helper: require './helper'
require './filters'
require './shape_children'
require './shapes'
require './widgets'