# generated by Neptune Namespaces v2.x.x
# file: tests/Art/Engine/Elements/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Helper: require './Helper'
require './Filters'
require './ShapeChildren'
require './Shapes'
require './Widgets'