# generated by Neptune Namespaces v2.x.x
# file: tests/Art/Engine/Elements/namespace.coffee

Engine = require '../namespace'
module.exports = Engine.Elements ||
Engine.addNamespace 'Elements', class Elements extends Neptune.Base
  ;
require './Filters/namespace';
require './ShapeChildren/namespace';
require './Shapes/namespace';
require './Widgets/namespace'