# generated by Neptune Namespaces v0.5
# file: tests/art/engine/elements/namespace.coffee

Engine = require '../namespace'
module.exports = Engine.Elements ||
Engine.addNamespace 'Elements', class Elements extends Neptune.Base
  ;