# generated by Neptune Namespaces v0.1.0
# file: tests/art/engine/elements/namespace.coffee

Engine = require '../namespace'
module.exports = Engine.Elements ||
Engine.addNamespace class Elements extends Neptune.Base
  ;