// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Engine/Elements/Widgets/index.js

(module.exports = require('./namespace'))

.addModules({
  PagingScrollElement: require('./PagingScrollElement'),
  ScrollElement:       require('./ScrollElement')
});