# generated by Neptune Namespaces v3.x.x
# file: tests/Art.Engine/Elements/Widgets/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  PagingScrollElement: require './PagingScrollElement'
  ScrollElement2:      require './ScrollElement2'     