// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Engine/Core/Drawing/index.js

(module.exports = require('./namespace'))

.addModules({
  Basics:         require('./Basics'),
  Clipping:       require('./Clipping'),
  DrawOrder:      require('./DrawOrder'),
  ElementDrawLib: require('./ElementDrawLib'),
  PartialRedraw:  require('./PartialRedraw'),
  Retina:         require('./Retina'),
  ToBitmap:       require('./toBitmap')
});
require('./CachingAndStaging');