// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Engine/Core/Drawing/namespace.js

module.exports = require('../namespace').addNamespace(
  'Drawing',
  class Drawing extends Neptune.PackageNamespace {}
);
require('./CachingAndStaging/namespace');