# generated by Neptune Namespaces v3.x.x
# file: tests/Engine/Core/namespace.coffee

module.exports = (require '../namespace').addNamespace('Core', class Core extends Neptune.PackageNamespace)
require './Drawing/namespace';
require './Element/namespace';
require './Layout/namespace'