# generated by Neptune Namespaces v3.x.x
# file: perfs/Art.Engine/namespace.coffee

module.exports = (require '../namespace').addNamespace 'Art.Engine', class Engine extends Neptune.PackageNamespace
  @version: require('../../../package.json').version
