// generated by Neptune Namespaces v4.x.x
// file: perfs/Art.Engine/namespace.js

module.exports = require('../namespace').addNamespace(
  'Art.Engine',
  (class Engine extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../../package.json'))
);
