# generated by Neptune Namespaces v2.x.x
# file: Art/Engine/Forms/namespace.coffee

Engine = require '../namespace'
module.exports = Engine.Forms ||
Engine.addNamespace 'Forms', class Forms extends Neptune.Base
  ;
