// generated by Neptune Namespaces v4.x.x
// file: Art/Engine/Forms/namespace.js

module.exports = require('../namespace').addNamespace(
  'Forms',
  class Forms extends Neptune.PackageNamespace {}
);
