# generated by Neptune Namespaces
# file: tests/art/engine/index.coffee

module.exports =
Engine           = require './namespace'
Engine.Animation = require './animation'
Engine.Core      = require './core'
Engine.Elements  = require './elements'
Engine.Events    = require './events'
Engine.File      = require './file'
Engine.Layout    = require './layout'
Engine.finishLoad(
  []
)