# generated by Neptune Namespaces v1.x.x
# file: tests/art/engine/index.coffee

module.exports = require './namespace'
.addModules
  TestHelper: require './test_helper'
require './animation'
require './core'
require './elements'
require './events'
require './file'
require './layout'