# generated by Neptune Namespaces v2.x.x
# file: tests/Art/Engine/namespace.coffee

Art = require '../namespace'
module.exports = Art.Engine ||
Art.addNamespace 'Engine', class Engine extends Neptune.Base
  ;
require './Core/namespace';
require './Elements/namespace';
require './Events/namespace';
require './File/namespace';
require './Layout/namespace';
require './ZAnimation/namespace'