# generated by Neptune Namespaces v1.x.x
# file: tests/Art/Engine/namespace.coffee

Art = require '../namespace'
module.exports = Art.Engine ||
Art.addNamespace 'Engine', class Engine extends Neptune.Base
  ;