# generated by Neptune Namespaces v3.x.x
# file: tests/Engine/Core/Drawing/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Basics:        require './Basics'       
  Clipping:      require './Clipping'     
  PartialRedraw: require './PartialRedraw'
  Retina:        require './Retina'       
  ToBitmap:      require './toBitmap'     