# generated by Neptune Namespaces v3.x.x
# file: tests/Engine/Core/Drawing/namespace.coffee

module.exports = (require '../namespace').addNamespace('Drawing', class Drawing extends Neptune.PackageNamespace)
