# generated by Neptune Namespaces v2.x.x
# file: tests/Art/Engine/ZAnimation/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Animator:           require './Animator'          
  PersistantAnimator: require './PersistantAnimator'