# generated by Neptune Namespaces v1.x.x
# file: tests/Art/Engine/ZAnimation/namespace.coffee

Engine = require '../namespace'
module.exports = Engine.ZAnimation ||
Engine.addNamespace 'ZAnimation', class ZAnimation extends Neptune.Base
  ;