# generated by Neptune Namespaces v1.x.x
# file: Art/namespace.coffee

Neptune = require 'neptune-namespaces'
module.exports = Neptune.Art ||
Neptune.addNamespace 'Art', class Art extends Neptune.Base
  ;