# generated by Neptune Namespaces
# file: art/engine/events/index.coffee

(module.exports = require './namespace')
.addModules
  GestureRecognizer:   require './gesture_recognizer'
  KeyEvent:            require './key_event'
  Pointer:             require './pointer'
  PointerEvent:        require './pointer_event'
  PointerEventManager: require './pointer_event_manager'
