# generated by Neptune Namespaces v1.x.x
# file: art/engine/events/index.coffee

module.exports = require './namespace'
.addModules
  GestureRecognizer:   require './gesture_recognizer'   
  KeyEvent:            require './key_event'            
  PointerEventManager: require './pointer_event_manager'
  PointerEvent:        require './pointer_event'        
  Pointer:             require './pointer'              