# generated by Neptune Namespaces v0.4.1
# file: art/engine/events/namespace.coffee

Engine = require '../namespace'
module.exports = Engine.Events ||
Engine.addNamespace 'Events', class Events extends Neptune.Base
  ;