# generated by Neptune Namespaces
# file: art/engine/events/namespace.coffee

Engine = require '../namespace'
module.exports = Engine.Events ||
Engine.addNamespace class Events extends Neptune.Base
  ;