# generated by Neptune Namespaces v3.x.x
# file: Art/Engine/Core/EpochLayout/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  FlexLayout:       require './FlexLayout'      
  Infinity:         require './Infinity'        
  LayoutTools:      require './LayoutTools'     
  StateEpochLayout: require './StateEpochLayout'