# generated by Neptune Namespaces v1.x.x
# file: Art/Engine/Core/EpochLayout/index.coffee

module.exports = require './namespace'
.addModules
  Basics:           require './Basics'          
  FlexLayout:       require './FlexLayout'      
  Infinity:         require './Infinity'        
  StateEpochLayout: require './StateEpochLayout'