# generated by Neptune Namespaces v3.x.x
# file: Art/Engine/Core/EpochLayout/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Basics:           require './Basics'          
  FlexLayout:       require './FlexLayout'      
  Infinity:         require './Infinity'        
  StateEpochLayout: require './StateEpochLayout'