// generated by Neptune Namespaces v4.x.x
// file: Art/Engine/Core/EpochLayout/index.js

(module.exports = require('./namespace'))

.addModules({
  FlexLayout:       require('./FlexLayout'),
  FlowLayout:       require('./FlowLayout'),
  Infinity:         require('./Infinity'),
  LayoutTools:      require('./LayoutTools'),
  StateEpochLayout: require('./StateEpochLayout')
});