// generated by Neptune Namespaces v4.x.x
// file: Art/Engine/Core/EpochLayout/namespace.js

module.exports = require('../namespace').addNamespace(
  'EpochLayout',
  class EpochLayout extends Neptune.PackageNamespace {}
);
