# generated by Neptune Namespaces v2.x.x
# file: Art/Engine/Core/EpochLayout/namespace.coffee

Core = require '../namespace'
module.exports = Core.EpochLayout ||
Core.addNamespace 'EpochLayout', class EpochLayout extends Neptune.Base
  ;
