# generated by Neptune Namespaces v3.x.x
# file: Art/Engine/Core/EpochLayout/namespace.coffee

module.exports = (require '../namespace').addNamespace('EpochLayout', class EpochLayout extends Neptune.PackageNamespace)
