// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Engine/Events/index.js

(module.exports = require('./namespace'))

.addModules({
  PointerEvent:        require('./PointerEvent'),
  PointerEventManager: require('./PointerEventManager')
});