# generated by Neptune Namespaces v3.x.x
# file: tests/Art.Engine/Events/namespace.coffee

module.exports = (require '../namespace').addNamespace('Events', class Events extends Neptune.PackageNamespace)
