// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Engine/Elements/Shapes/index.js

(module.exports = require('./namespace'))

.addModules({
  BitmapElement:    require('./BitmapElement'),
  RectangleElement: require('./RectangleElement'),
  TextElement:      require('./TextElement'),
  TextElement2:     require('./TextElement2')
});