# generated by Neptune Namespaces v3.x.x
# file: tests/Art.Engine/Elements/Shapes/namespace.coffee

module.exports = (require '../namespace').addNamespace('Shapes', class Shapes extends Neptune.PackageNamespace)
