// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Engine/Elements/Shapes/namespace.js

module.exports = require('../namespace').addNamespace(
  'Shapes',
  class Shapes extends Neptune.PackageNamespace {}
);
