# generated by Neptune Namespaces
# file: art/engine/elements/shapes/index.coffee

module.exports =
Shapes                    = require './namespace'
Shapes.BitmapElement      = require './bitmap_element'
Shapes.CustomShapeElement = require './custom_shape_element'
Shapes.Rectangle          = require './rectangle'
Shapes.TextElement        = require './text_element'
Shapes.finishLoad(
  ["BitmapElement","CustomShapeElement","Rectangle","TextElement"]
)