# generated by Neptune Namespaces
# file: art/engine/elements/shapes/index.coffee

(module.exports = require './namespace')
.addModules
  BitmapElement:    require './bitmap_element'
  RectangleElement: require './rectangle_element'
  ShapeElement:     require './shape_element'
  TextElement:      require './text_element'
