# generated by Neptune Namespaces v0.3.0
# file: art/engine/elements/shapes/namespace.coffee

Elements = require '../namespace'
module.exports = Elements.Shapes ||
Elements.addNamespace 'Shapes', class Shapes extends Neptune.Base
  ;