# generated by Neptune Namespaces v3.x.x
# file: tests/Engine/Elements/Shapes/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  BitmapElement:    require './BitmapElement'   
  RectangleElement: require './RectangleElement'
  TextElement:      require './TextElement'     
  TextElement2:     require './TextElement2'    