# generated by Neptune Namespaces v3.x.x
# file: tests/Engine/Core/Layout/Flex/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  ChildrenRelative:     require './ChildrenRelative'    
  CircularDependencies: require './CircularDependencies'
  Column:               require './Column'              
  Margins:              require './Margins'             
  MaxLayout:            require './MaxLayout'           
  Regressions:          require './Regressions'         
  Row:                  require './Row'                 