# generated by Neptune Namespaces v3.x.x
# file: tests/Art.Engine/Core/Drawing/CachingAndStaging/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  CacheDraw:          require './CacheDraw'         
  DrawThroughCache:   require './DrawThroughCache'  
  IncrementalCaching: require './IncrementalCaching'