// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Engine/Core/Drawing/CachingAndStaging/index.js

(module.exports = require('./namespace'))

.addModules({
  CacheDraw:        require('./CacheDraw'),
  CacheDraw2:       require('./CacheDraw2'),
  DrawThroughCache: require('./DrawThroughCache'),
  PartialCacheDraw: require('./PartialCacheDraw')
});