// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Engine/Core/Drawing/CachingAndStaging/namespace.js

module.exports = require('../namespace').addNamespace(
  'CachingAndStaging',
  class CachingAndStaging extends Neptune.PackageNamespace {}
);
