# generated by Neptune Namespaces v3.x.x
# file: tests/Art.Engine/Core/Drawing/CachingAndStaging/namespace.coffee

module.exports = (require '../namespace').addNamespace('CachingAndStaging', class CachingAndStaging extends Neptune.PackageNamespace)
