# generated by Neptune Namespaces v3.x.x
# file: tests/Art.Engine/Core/Layout/Flex/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  ChildrenRelative:     require './ChildrenRelative'    
  CircularDependencies: require './CircularDependencies'
  Column:               require './Column'              
  Margins:              require './Margins'             
  MaxLayout:            require './MaxLayout'           
  Overconstrained:      require './Overconstrained'     
  Regressions:          require './Regressions'         
  Row:                  require './Row'                 
  Row2:                 require './Row2'                