// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Engine/Core/Layout/Flex/index.js

(module.exports = require('./namespace'))

.addModules({
  ChildrenRelative:     require('./ChildrenRelative'),
  CircularDependencies: require('./CircularDependencies'),
  Column:               require('./Column'),
  Margins:              require('./Margins'),
  MaxLayout:            require('./MaxLayout'),
  Overconstrained:      require('./Overconstrained'),
  Regressions:          require('./Regressions'),
  Row:                  require('./Row'),
  Row2:                 require('./Row2')
});