# generated by Neptune Namespaces v3.x.x
# file: tests/Art.Engine/Core/Layout/Flex/namespace.coffee

module.exports = (require '../namespace').addNamespace('Flex', class Flex extends Neptune.PackageNamespace)
