// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Engine/Core/Layout/Flex/namespace.js

module.exports = require('../namespace').addNamespace(
  'Flex',
  class Flex extends Neptune.PackageNamespace {}
);
