# generated by Neptune Namespaces v3.x.x
# file: tests/Art.Engine/Core/Layout/Flow/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Basics:            require './Basics'           
  ChildrenAlignment: require './ChildrenAlignment'
  ChildrenRelative:  require './ChildrenRelative' 
  Margins:           require './Margins'          
  Padding:           require './Padding'          