// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Engine/Core/Layout/Flow/index.js

(module.exports = require('./namespace'))

.addModules({
  Basics:            require('./Basics'),
  ChildrenAlignment: require('./ChildrenAlignment'),
  ChildrenRelative:  require('./ChildrenRelative'),
  Margins:           require('./Margins'),
  Padding:           require('./Padding')
});