# generated by Neptune Namespaces v3.x.x
# file: tests/Art.Engine/Core/Layout/Flow/namespace.coffee

module.exports = (require '../namespace').addNamespace('Flow', class Flow extends Neptune.PackageNamespace)
