// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Engine/Core/Layout/Flow/namespace.js

module.exports = require('../namespace').addNamespace(
  'Flow',
  class Flow extends Neptune.PackageNamespace {}
);
