# generated by Neptune Namespaces v3.x.x
# file: tests/Engine/Core/Layout/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  CommentInspiredLayout: require './CommentInspiredLayout'
  TextElement:           require './TextElement'          
require './Flex'
require './Flow'
require './Functional'