# generated by Neptune Namespaces v3.x.x
# file: tests/Art.Engine/Core/Element/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Basics:    require './Basics'   
  CacheDraw: require './CacheDraw'