// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Engine/Core/Element/namespace.js

module.exports = require('../namespace').addNamespace(
  'Element',
  class Element extends Neptune.PackageNamespace {}
);
