# generated by Neptune Namespaces v3.x.x
# file: tests/Art.Engine/Core/Element/namespace.coffee

module.exports = (require '../namespace').addNamespace('Element', class Element extends Neptune.PackageNamespace)
