// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Engine/Core/index.js

(module.exports = require('./namespace'))

.addModules({
  CoreHelper:              require('./CoreHelper'),
  DrawAreaHelpers:         require('./DrawAreaHelpers'),
  ElementChildren:         require('./ElementChildren'),
  ElementDrawArea:         require('./ElementDrawArea'),
  ElementDrawArea2:        require('./ElementDrawArea2'),
  ElementExtending:        require('./ElementExtending'),
  ElementFamilyEvents:     require('./ElementFamilyEvents'),
  ElementGeometry:         require('./ElementGeometry'),
  ElementInstanceRegistry: require('./ElementInstanceRegistry'),
  ElementPointerEvents:    require('./ElementPointerEvents'),
  ElementStateEpoch:       require('./ElementStateEpoch'),
  EpochedElementMixin:     require('./EpochedElementMixin'),
  MultitouchManager:       require('./MultitouchManager'),
  StateEpochTestHelper:    require('./StateEpochTestHelper')
});
require('./Drawing');
require('./Element');
require('./Layout');