# generated by Neptune Namespaces v3.x.x
# file: tests/Art.Engine/Core/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  CoreHelper:              require './CoreHelper'             
  DrawAreaHelpers:         require './DrawAreaHelpers'        
  ElementChildren:         require './ElementChildren'        
  ElementDrawArea:         require './ElementDrawArea'        
  ElementDrawArea2:        require './ElementDrawArea2'       
  ElementExtending:        require './ElementExtending'       
  ElementFamilyEvents:     require './ElementFamilyEvents'    
  ElementGeometry:         require './ElementGeometry'        
  ElementInstanceRegistry: require './ElementInstanceRegistry'
  ElementPointerEvents:    require './ElementPointerEvents'   
  ElementStateEpoch:       require './ElementStateEpoch'      
  EpochedElementMixin:     require './EpochedElementMixin'    
  MultitouchManager:       require './MultitouchManager'      
  StateEpochTestHelper:    require './StateEpochTestHelper'   
require './Drawing'
require './Element'
require './Layout'