# generated by Neptune Namespaces v3.x.x
# file: Art/Engine/Elements/Widgets/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  PagingScrollElement:   require './PagingScrollElement'  
  ScrollElement:         require './ScrollElement'        
  ScrollElementAnimator: require './ScrollElementAnimator'