// generated by Neptune Namespaces v4.x.x
// file: Art/Engine/Elements/Widgets/namespace.js

module.exports = require('../namespace').addNamespace(
  'Widgets',
  class Widgets extends Neptune.PackageNamespace {}
);
