# generated by Neptune Namespaces v1.x.x
# file: Art/Engine/Elements/Widgets/namespace.coffee

Elements = require '../namespace'
module.exports = Elements.Widgets ||
Elements.addNamespace 'Widgets', class Widgets extends Neptune.Base
  ;