# generated by Neptune Namespaces v3.x.x
# file: Art/Engine/Elements/Widgets/namespace.coffee

module.exports = (require '../namespace').addNamespace('Widgets', class Widgets extends Neptune.PackageNamespace)
