# generated by Neptune Namespaces v0.1.0
# file: tests/art/engine/core/layout/index.coffee

(module.exports = require './namespace')
.addModules
  ElementChildrenLayoutColumn: require './element_children_layout_column'
  ElementChildrenLayoutFlow:   require './element_children_layout_flow'
  ElementChildrenLayoutGrid:   require './element_children_layout_grid'
  ElementChildrenLayoutRow:    require './element_children_layout_row'
  ElementLayoutMargin:         require './element_layout_margin'
  ElementLayoutPadding:        require './element_layout_padding'
  ElementPointLayout:          require './element_point_layout'
  TextElement:                 require './text_element'