# generated by Neptune Namespaces v1.x.x
# file: tests/Art/Engine/Core/Layout/index.coffee

module.exports = require './namespace'
.addModules
  ChildrenRelative:            require './ChildrenRelative'           
  ElementChildrenLayoutColumn: require './ElementChildrenLayoutColumn'
  ElementChildrenLayoutFlow:   require './ElementChildrenLayoutFlow'  
  ElementChildrenLayoutGrid:   require './ElementChildrenLayoutGrid'  
  ElementChildrenLayoutRow:    require './ElementChildrenLayoutRow'   
  ElementLayoutMargin:         require './ElementLayoutMargin'        
  ElementLayoutPadding:        require './ElementLayoutPadding'       
  ElementPointLayout:          require './ElementPointLayout'         
  Scale:                       require './Scale'                      
  TextElement:                 require './TextElement'                