# generated by Neptune Namespaces v1.x.x
# file: tests/art/engine/core/layout/namespace.coffee

Core = require '../namespace'
module.exports = Core.Layout ||
Core.addNamespace 'Layout', class Layout extends Neptune.Base
  ;