# generated by Neptune Namespaces
# file: test/tests/art/engine/core/layout/namespace.coffee

Core = require '../namespace'
module.exports = Core.Layout ||
class Core.Layout extends Neptune.Base
  @namespace: Core
  @namespacePath: "Neptune.Tests.Art.Engine.Core.Layout"

Core.addNamespace Core.Layout