# generated by Neptune Namespaces v2.x.x
# file: tests/Art/Engine/Core/Layout/namespace.coffee

Core = require '../namespace'
module.exports = Core.Layout ||
Core.addNamespace 'Layout', class Layout extends Neptune.Base
  ;
