# generated by Neptune Namespaces v0.1.0
# file: tests/art/engine/core/layout/namespace.coffee

Core = require '../namespace'
module.exports = Core.Layout ||
Core.addNamespace class Layout extends Neptune.Base
  ;