# generated by Neptune Namespaces v3.x.x
# file: tests/Art/Engine/Core/Layout/namespace.coffee

module.exports = (require '../namespace').addNamespace('Layout', class Layout extends Neptune.PackageNamespace)
