# generated by Neptune Namespaces v3.x.x
# file: tests/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  ArtEngineFactories: require './ArtEngineFactories'
require './Art.Engine'