# generated by Neptune Namespaces v0.4.1
# file: tests/namespace.coffee

require 'neptune-namespaces'
module.exports = Neptune.Tests ||
Neptune.addNamespace 'Tests', class Tests extends Neptune.Base
  ;