# generated by Neptune Namespaces
# file: tests/namespace.coffee

require 'neptune-namespaces'
module.exports = Neptune.Tests ||
class Neptune.Tests extends Neptune.Base
  @namespace: Neptune
  @namespacePath: "Neptune.Tests"

Neptune.addNamespace Neptune.Tests