mv ./Art/Engine/Animation/animator.coffee ./Art/Engine/Animation/Animator.coffee
mv ./Art/Engine/Animation/persistant_animator.coffee ./Art/Engine/Animation/PersistantAnimator.coffee
mv ./Art/Engine/Core/Element/basics.coffee ./Art/Engine/Core/Element/Basics.coffee
mv ./Art/Engine/Core/Element/cache_draw.coffee ./Art/Engine/Core/Element/CacheDraw.coffee
mv ./Art/Engine/Core/Element/drawing.coffee ./Art/Engine/Core/Element/Drawing.coffee
mv ./Art/Engine/Core/element_children.coffee ./Art/Engine/Core/ElementChildren.coffee
mv ./Art/Engine/Core/element_drawArea.coffee ./Art/Engine/Core/ElementDrawArea.coffee
mv ./Art/Engine/Core/element_extending.coffee ./Art/Engine/Core/ElementExtending.coffee
mv ./Art/Engine/Core/element_family_events.coffee ./Art/Engine/Core/ElementFamilyEvents.coffee
mv ./Art/Engine/Core/element_geometry.coffee ./Art/Engine/Core/ElementGeometry.coffee
mv ./Art/Engine/Core/element_instance_registry.coffee ./Art/Engine/Core/ElementInstanceRegistry.coffee
mv ./Art/Engine/Core/element_pointer_events.coffee ./Art/Engine/Core/ElementPointerEvents.coffee
mv ./Art/Engine/Core/element_state_epoch.coffee ./Art/Engine/Core/ElementStateEpoch.coffee
mv ./Art/Engine/Core/epoched_object.coffee ./Art/Engine/Core/EpochedObject.coffee
mv ./Art/Engine/Core/Layout/children_relative.coffee ./Art/Engine/Core/Layout/ChildrenRelative.coffee
mv ./Art/Engine/Core/Layout/element_children_layout_column.coffee ./Art/Engine/Core/Layout/ElementChildrenLayoutColumn.coffee
mv ./Art/Engine/Core/Layout/element_children_layout_flow.coffee ./Art/Engine/Core/Layout/ElementChildrenLayoutFlow.coffee
mv ./Art/Engine/Core/Layout/element_children_layout_grid.coffee ./Art/Engine/Core/Layout/ElementChildrenLayoutGrid.coffee
mv ./Art/Engine/Core/Layout/element_children_layout_row.coffee ./Art/Engine/Core/Layout/ElementChildrenLayoutRow.coffee
mv ./Art/Engine/Core/Layout/element_layout_margin.coffee ./Art/Engine/Core/Layout/ElementLayoutMargin.coffee
mv ./Art/Engine/Core/Layout/element_layout_padding.coffee ./Art/Engine/Core/Layout/ElementLayoutPadding.coffee
mv ./Art/Engine/Core/Layout/element_point_layout.coffee ./Art/Engine/Core/Layout/ElementPointLayout.coffee
mv ./Art/Engine/Core/Layout/scale.coffee ./Art/Engine/Core/Layout/Scale.coffee
mv ./Art/Engine/Core/Layout/text_element.coffee ./Art/Engine/Core/Layout/TextElement.coffee
mv ./Art/Engine/Core/state_epoch_test_helper.coffee ./Art/Engine/Core/StateEpochTestHelper.coffee
mv ./Art/Engine/Elements/Filters/blur_element.coffee ./Art/Engine/Elements/Filters/BlurElement.coffee
mv ./Art/Engine/Elements/Filters/filter_element.coffee ./Art/Engine/Elements/Filters/FilterElement.coffee
mv ./Art/Engine/Elements/Filters/shadow_element.coffee ./Art/Engine/Elements/Filters/ShadowElement.coffee
mv ./Art/Engine/Elements/Helper.coffee ./Art/Engine/Elements/Helper.coffee
mv ./Art/Engine/Elements/ShapeChildren/outline_element.coffee ./Art/Engine/Elements/ShapeChildren/OutlineElement.coffee
mv ./Art/Engine/Elements/Shapes/bitmap_element.coffee ./Art/Engine/Elements/Shapes/BitmapElement.coffee
mv ./Art/Engine/Elements/Shapes/rectangle_element.coffee ./Art/Engine/Elements/Shapes/RectangleElement.coffee
mv ./Art/Engine/Elements/Shapes/text_element.coffee ./Art/Engine/Elements/Shapes/TextElement.coffee
mv ./Art/Engine/Elements/Widgets/paging_scroll_element.coffee ./Art/Engine/Elements/Widgets/PagingScrollElement.coffee
mv ./Art/Engine/Events/pointer_event.coffee ./Art/Engine/Events/PointerEvent.coffee
mv ./Art/Engine/Events/pointer_event_manager.coffee ./Art/Engine/Events/PointerEventManager.coffee
mv ./Art/Engine/File/v1_writer.coffee ./Art/Engine/File/V1Writer.coffee
mv ./Art/Engine/Layout/point_layout.coffee ./Art/Engine/Layout/PointLayout.coffee
mv ./Art/Engine/test_helper.coffee ./Art/Engine/TestHelper.coffee
