# generated by Neptune Namespaces v1.x.x
# file: Art/Engine/Elements/index.coffee

module.exports = require './namespace'
.includeInNamespace require './Elements'
.addModules
  FillableBase:          require './FillableBase'         
  FilterAndFillableBase: require './FilterAndFillableBase'
require './Filters'
require './ShapeChildren'
require './Shapes'
require './Widgets'