// generated by Neptune Namespaces v4.x.x
// file: Art/Engine/Elements/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./Elements'))
.addModules({
  AtomElement:       require('./AtomElement'),
  ShadowableElement: require('./ShadowableElement')
});
require('./Filters');
require('./ShapeChildren');
require('./Shapes');
require('./Widgets');