# generated by Neptune Namespaces v1.x.x
# file: Art/Engine/Elements/index.coffee

module.exports = require './namespace'
.includeInNamespace require './Elements'
.addModules
  Base:         require './Base'        
  FillableBase: require './FillableBase'
require './Filters'
require './ShapeChildren'
require './Shapes'
require './Widgets'