# generated by Neptune Namespaces v1.x.x
# file: Art/Engine/Elements/namespace.coffee

Engine = require '../namespace'
module.exports = Engine.Elements ||
Engine.addNamespace 'Elements', class Elements extends Neptune.Base
  ;