// generated by Neptune Namespaces v4.x.x
// file: Art/Engine/Elements/namespace.js

module.exports = require('../namespace').addNamespace(
  'Elements',
  class Elements extends Neptune.PackageNamespace {}
);
require('./Filters/namespace');
require('./ShapeChildren/namespace');
require('./Shapes/namespace');
require('./Widgets/namespace');