# generated by Neptune Namespaces v3.x.x
# file: Art/Engine/Core/index.coffee

module.exports = require './namespace'
module.exports
.includeInNamespace require './Core'
.addModules
  AnimatedElementMixin: require './AnimatedElementMixin'
  CanvasElement:        require './CanvasElement'       
  Element:              require './Element'             
  ElementBase:          require './ElementBase'         
  ElementFactory:       require './ElementFactory'      
  EngineStat:           require './EngineStat'          
  EpochedElementMixin:  require './EpochedElementMixin' 
  EventedElementMixin:  require './EventedElementMixin' 
  GlobalEpochCycle:     require './GlobalEpochCycle'    
  IdleEpoch:            require './IdleEpoch'           
  Lib:                  require './Lib'                 
  SourceToBitmapCache:  require './SourceToBitmapCache' 
  StandardImport:       require './StandardImport'      
  StateEpoch:           require './StateEpoch'          
require './Drawing'
require './EpochLayout'