# generated by Neptune Namespaces v2.x.x
# file: Art/Engine/Core/index.coffee

module.exports = require './namespace'
module.exports
.includeInNamespace require './Core'
.addModules
  CanvasElement:        require './CanvasElement'       
  DrawCacheManager:     require './DrawCacheManager'    
  DrawEpoch:            require './DrawEpoch'           
  Element:              require './Element'             
  ElementBase:          require './ElementBase'         
  ElementFactory:       require './ElementFactory'      
  EngineStat:           require './EngineStat'          
  EpochedObject:        require './EpochedObject'       
  EventedEpochedObject: require './EventedEpochedObject'
  GlobalEpochCycle:     require './GlobalEpochCycle'    
  IdleEpoch:            require './IdleEpoch'           
  StateEpoch:           require './StateEpoch'          
require './EpochLayout'