# generated by Neptune Namespaces v2.x.x
# file: Art/Engine/Core/namespace.coffee

Engine = require '../namespace'
module.exports = Engine.Core ||
Engine.addNamespace 'Core', class Core extends Neptune.Base
  ;
require './EpochLayout/namespace'