// generated by Neptune Namespaces v4.x.x
// file: Art/Engine/Core/namespace.js

module.exports = require('../namespace').addNamespace(
  'Core',
  class Core extends Neptune.PackageNamespace {}
);
require('./Drawing/namespace');
require('./EpochLayout/namespace');