# generated by Neptune Namespaces v3.x.x
# file: Art/Engine/Core/namespace.coffee

module.exports = (require '../namespace').addNamespace('Core', class Core extends Neptune.PackageNamespace)
require './EpochLayout/namespace'