// generated by Neptune Namespaces v4.x.x
// file: Art/Engine/Core/Drawing/index.js

(module.exports = require('./namespace'))

.addModules({
  DrawAreaCollector:    require('./DrawAreaCollector'),
  DrawCacheManager:     require('./DrawCacheManager'),
  DrawEpoch:            require('./DrawEpoch'),
  ElementDrawAreaMixin: require('./ElementDrawAreaMixin'),
  ElementDrawLib:       require('./ElementDrawLib'),
  ElementDrawMixin:     require('./ElementDrawMixin')
});