# generated by Neptune Namespaces v1.x.x
# file: tests/art/engine/elements/filters/index.coffee

module.exports = require './namespace'
.addModules
  BlurElement:   require './blur_element'  
  FilterElement: require './filter_element'
  ShadowElement: require './shadow_element'