# generated by Neptune Namespaces
# file: tests/art/engine/elements/filters/index.coffee

module.exports =
Filters        = require './namespace'
Filters.Blur   = require './blur'
Filters.Filter = require './filter'
Filters.Shadow = require './shadow'
Filters.finishLoad(
  ["Blur","Filter","Shadow"]
)