# generated by Neptune Namespaces v0.3.0
# file: tests/art/engine/elements/filters/namespace.coffee

Elements = require '../namespace'
module.exports = Elements.Filters ||
Elements.addNamespace 'Filters', class Filters extends Neptune.Base
  ;