# generated by Neptune Namespaces
# file: tests/art/engine/elements/filters/namespace.coffee

Elements = require '../namespace'
module.exports = Elements.Filters ||
class Elements.Filters extends Neptune.Base
  @namespace: Elements
  @namespacePath: "Neptune.Tests.Art.Engine.Elements.Filters"

Elements.addNamespace Elements.Filters