# generated by Neptune Namespaces v2.x.x
# file: tests/Art/Engine/Elements/Filters/namespace.coffee

Elements = require '../namespace'
module.exports = Elements.Filters ||
Elements.addNamespace 'Filters', class Filters extends Neptune.Base
  ;
