# generated by Neptune Namespaces
# this file: src/art/engine/dev_tools/index.coffee

module.exports =
DevTools                  = require './namespace'
DevTools.GlobalEpochStats = require './global_epoch_stats'
DevTools.finishLoad(
  ["GlobalEpochStats"]
)