# generated by Neptune Namespaces v0.5
# file: art/engine/dev_tools/namespace.coffee

Engine = require '../namespace'
module.exports = Engine.DevTools ||
Engine.addNamespace 'DevTools', class DevTools extends Neptune.Base
  ;