# generated by Neptune Namespaces v0.1.0
# file: art/engine/dev_tools/namespace.coffee

Engine = require '../namespace'
module.exports = Engine.DevTools ||
Engine.addNamespace class DevTools extends Neptune.Base
  ;