# generated by Neptune Namespaces v3.x.x
# file: tests/Engine/ZAnimation/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Animator:           require './Animator'          
  PersistantAnimator: require './PersistantAnimator'