# generated by Neptune Namespaces v3.x.x
# file: tests/Engine/ZAnimation/namespace.coffee

module.exports = (require '../namespace').addNamespace('ZAnimation', class ZAnimation extends Neptune.PackageNamespace)
