// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Engine/Elements/index.js

(module.exports = require('./namespace'))

.addModules({
  Helper: require('./Helper')
});
require('./Filters');
require('./ShapeChildren');
require('./Shapes');
require('./Widgets');