# generated by Neptune Namespaces v3.x.x
# file: tests/Art.Engine/Elements/namespace.coffee

module.exports = (require '../namespace').addNamespace('Elements', class Elements extends Neptune.PackageNamespace)
require './Filters/namespace';
require './ShapeChildren/namespace';
require './Shapes/namespace';
require './Widgets/namespace'