# generated by Neptune Namespaces v0.5
# file: art/engine/elements/filters/index.coffee

module.exports = require './namespace'
.addModules
  BlurElement:   require './blur_element'  
  FilterElement: require './filter_element'
  ShadowElement: require './shadow_element'