# generated by Neptune Namespaces v0.1.0
# file: art/engine/elements/filters/namespace.coffee

Elements = require '../namespace'
module.exports = Elements.Filters ||
Elements.addNamespace class Filters extends Neptune.Base
  ;