# generated by Neptune Namespaces
# file: art/engine/file/index.coffee

module.exports =
File          = require './namespace'
File.V1Loader = require './v1_loader'
File.V1Writer = require './v1_writer'
File.finishLoad(
  ["V1Loader","V1Writer"]
)