# generated by Neptune Namespaces
# file: art/engine/file/index.coffee

module.exports =
File          = require './namespace'
File.Model    = require './model'
File.V1Loader = require './v1_loader'
File.finishLoad(
  ["Model","V1Loader"]
)