# generated by Neptune Namespaces
# file: src/art/engine/file/namespace.coffee

Engine = require '../namespace'
module.exports = Engine.File ||
class Engine.File extends Neptune.Base
  @namespace: Engine
  @namespacePath: "Neptune.Art.Engine.File"

Engine.addNamespace Engine.File