# generated by Neptune Namespaces v0.4.1
# file: art/engine/file/namespace.coffee

Engine = require '../namespace'
module.exports = Engine.File ||
Engine.addNamespace 'File', class File extends Neptune.Base
  ;