// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Engine/ZAnimation/index.js

(module.exports = require('./namespace'))

.addModules({
  Animator:           require('./Animator'),
  PersistantAnimator: require('./PersistantAnimator')
});