// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Engine/ZAnimation/namespace.js

module.exports = require('../namespace').addNamespace(
  'ZAnimation',
  class ZAnimation extends Neptune.PackageNamespace {}
);
