# generated by Neptune Namespaces v3.x.x
# file: tests/Engine/Elements/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Helper: require './Helper'
require './Filters'
require './ShapeChildren'
require './Shapes'
require './Widgets'