# generated by Neptune Namespaces v0.5
# file: tests/art/engine/core/index.coffee

module.exports = require './namespace'
.addModules
  ElementChildren:         require './element_children'         
  ElementDrawArea:         require './element_drawArea'         
  ElementExtending:        require './element_extending'        
  ElementFamilyEvents:     require './element_family_events'    
  ElementGeometry:         require './element_geometry'         
  ElementInstanceRegistry: require './element_instance_registry'
  ElementPointerEvents:    require './element_pointer_events'   
  ElementStateEpoch:       require './element_state_epoch'      
  EpochedObject:           require './epoched_object'           
  StateEpochTestHelper:    require './state_epoch_test_helper'  
require './element'
require './layout'