# generated by Neptune Namespaces v2.x.x
# file: tests/Art/Engine/Core/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  CoreHelper:              require './CoreHelper'             
  ElementChildren:         require './ElementChildren'        
  ElementDrawArea:         require './ElementDrawArea'        
  ElementExtending:        require './ElementExtending'       
  ElementFamilyEvents:     require './ElementFamilyEvents'    
  ElementGeometry:         require './ElementGeometry'        
  ElementInstanceRegistry: require './ElementInstanceRegistry'
  ElementPointerEvents:    require './ElementPointerEvents'   
  ElementStateEpoch:       require './ElementStateEpoch'      
  EpochedObject:           require './EpochedObject'          
  StateEpochTestHelper:    require './StateEpochTestHelper'   
require './Drawing'
require './Element'
require './Layout'