# generated by Neptune Namespaces
# file: tests/art/engine/core/namespace.coffee

Engine = require '../namespace'
module.exports = Engine.Core ||
Engine.addNamespace class Core extends Neptune.Base
  ;