# generated by Neptune Namespaces v2.x.x
# file: tests/Art/Engine/Core/namespace.coffee

Engine = require '../namespace'
module.exports = Engine.Core ||
Engine.addNamespace 'Core', class Core extends Neptune.Base
  ;
require './Drawing/namespace';
require './Element/namespace';
require './Layout/namespace'