# generated by Neptune Namespaces v0.5
# file: tests/art/engine/core/namespace.coffee

Engine = require '../namespace'
module.exports = Engine.Core ||
Engine.addNamespace 'Core', class Core extends Neptune.Base
  ;