# generated by Neptune Namespaces v1.x.x
# file: art/engine/elements/widgets/index.coffee

module.exports = require './namespace'
.addModules
  PagingScrollElementWip: require './paging_scroll_element_wip'
  PagingScrollElement:    require './paging_scroll_element'    