# generated by Neptune Namespaces v0.1.0
# file: art/engine/elements/widgets/index.coffee

(module.exports = require './namespace')
.addModules
  PagingScrollElement: require './paging_scroll_element'