# generated by Neptune Namespaces
# file: art/engine/elements/widgets/namespace.coffee

Elements = require '../namespace'
module.exports = Elements.Widgets ||
class Elements.Widgets extends Neptune.Base
  @namespace: Elements
  @namespacePath: "Neptune.Art.Engine.Elements.Widgets"

Elements.addNamespace Elements.Widgets