# generated by Neptune Namespaces v0.4.1
# file: art/engine/elements/widgets/namespace.coffee

Elements = require '../namespace'
module.exports = Elements.Widgets ||
Elements.addNamespace 'Widgets', class Widgets extends Neptune.Base
  ;