// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Engine/Core/Layout/index.js

(module.exports = require('./namespace'))

.addModules({
  CommentInspiredLayout: require('./CommentInspiredLayout'),
  TextElement:           require('./TextElement')
});
require('./Flex');
require('./Flow');
require('./Functional');