// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Engine/Core/Layout/namespace.js

module.exports = require('../namespace').addNamespace(
  'Layout',
  class Layout extends Neptune.PackageNamespace {}
);
require('./Flex/namespace');
require('./Flow/namespace');
require('./Functional/namespace');