# generated by Neptune Namespaces v0.3.0
# file: tests/art/engine/animation/index.coffee

(module.exports = require './namespace')
.addModules
  Animator:           require './animator'
  PersistantAnimator: require './persistant_animator'