# generated by Neptune Namespaces
# file: tests/art/engine/animation/index.coffee

module.exports =
Animation                    = require './namespace'
Animation.Animator           = require './animator'
Animation.PersistantAnimator = require './persistant_animator'
Animation.finishLoad(
  ["Animator","PersistantAnimator"]
)