# generated by Neptune Namespaces v1.x.x
# file: tests/Art/Engine/Animation/index.coffee

module.exports = require './namespace'
.addModules
  Animator:           require './Animator'          
  PersistantAnimator: require './PersistantAnimator'