# generated by Neptune Namespaces v0.5
# file: tests/art/engine/animation/namespace.coffee

Engine = require '../namespace'
module.exports = Engine.Animation ||
Engine.addNamespace 'Animation', class Animation extends Neptune.Base
  ;