# generated by Neptune Namespaces
# file: tests/art/engine/animation/namespace.coffee

Engine = require '../namespace'
module.exports = Engine.Animation ||
Engine.addNamespace class Animation extends Neptune.Base
  ;