# generated by Neptune Namespaces v3.x.x
# file: tests/Art/Engine/Elements/ShapeChildren/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  OutlineElement: require './OutlineElement'