# generated by Neptune Namespaces v0.3.0
# file: art/engine/index.coffee

(module.exports = require './namespace')
.includeInNamespace(require './_engine')
.addModules
  FullScreenApp: require './full_screen_app'
require './animation'
require './core'
require './dev_tools'
require './elements'
require './events'
require './file'
require './forms'
require './layout'