# generated by Neptune Namespaces v0.5
# file: art/engine/namespace.coffee

Art = require '../namespace'
module.exports = Art.Engine ||
Art.addNamespace 'Engine', class Engine extends Neptune.Base
  ;