// generated by Neptune Namespaces v4.x.x
// file: Art/Engine/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./Engine'))
.addModules({
  Config:         require('./Config'),
  DefaultProps:   require('./DefaultProps'),
  FullScreenApp:  require('./FullScreenApp'),
  Macros:         require('./Macros'),
  NormalizeProps: require('./NormalizeProps'),
  StandardImport: require('./StandardImport')
});
require('./Animation');
require('./Core');
require('./DevTools');
require('./Elements');
require('./Events');
require('./File');
require('./Forms');
require('./Layout');