# generated by Neptune Namespaces v2.x.x
# file: Art/Engine/namespace.coffee

Art = require '../namespace'
module.exports = Art.Engine ||
Art.addNamespace 'Engine', class Engine extends Neptune.Base
  ;
require './Animation/namespace';
require './Core/namespace';
require './DevTools/namespace';
require './Elements/namespace';
require './Events/namespace';
require './File/namespace';
require './Forms/namespace';
require './Layout/namespace'