// generated by Neptune Namespaces v4.x.x
// file: Art/Engine/namespace.js

module.exports = require('../namespace').addNamespace(
  'Engine',
  (class Engine extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../../package.json'))
);
require('./Animation/namespace');
require('./Core/namespace');
require('./Elements/namespace');
require('./Events/namespace');
require('./File/namespace');
require('./Forms/namespace');
require('./Layout/namespace');