# generated by Neptune Namespaces
# file: tests/art/engine/elements/shape_children/index.coffee

module.exports =
ShapeChildren                = require './namespace'
ShapeChildren.OutlineElement = require './outline_element'
ShapeChildren.finishLoad(
  ["OutlineElement"]
)