# generated by Neptune Namespaces v0.1.0
# file: tests/art/engine/elements/shape_children/index.coffee

(module.exports = require './namespace')
.addModules
  OutlineElement: require './outline_element'