# generated by Neptune Namespaces v1.x.x
# file: tests/art/engine/elements/shape_children/index.coffee

module.exports = require './namespace'
.addModules
  OutlineElement: require './outline_element'