# generated by Neptune Namespaces
# file: tests/art/engine/elements/shape_children/namespace.coffee

Elements = require '../namespace'
module.exports = Elements.ShapeChildren ||
Elements.addNamespace class ShapeChildren extends Neptune.Base
  ;