# generated by Neptune Namespaces v2.x.x
# file: tests/Art/namespace.coffee

Tests = require '../namespace'
module.exports = Tests.Art ||
Tests.addNamespace 'Art', class Art extends Neptune.Base
  ;
require './Engine/namespace'