# generated by Neptune Namespaces
# file: test/tests/art/namespace.coffee

Tests = require '../namespace'
module.exports = Tests.Art ||
class Tests.Art extends Neptune.Base
  @namespace: Tests
  @namespacePath: "Neptune.Tests.Art"

Tests.addNamespace Tests.Art