# generated by Neptune Namespaces
# file: art/engine/animation/index.coffee

module.exports =
Animation                          = require './namespace'
Animation.Animator                 = require './animator'
Animation.EasingFunctions          = require './easing_functions'
Animation.EasingPersistantAnimator = require './easing_persistant_animator'
Animation.PersistantAnimator       = require './persistant_animator'
Animation.finishLoad(
  ["Animator","EasingFunctions","EasingPersistantAnimator","PersistantAnimator"]
)