# generated by Neptune Namespaces v0.5
# file: art/engine/animation/index.coffee

module.exports = require './namespace'
.addModules
  Animator:                   require './animator'                    
  EasingFunctions:            require './easing_functions'            
  EasingPersistantAnimator:   require './easing_persistant_animator'  
  PeriodicPersistantAnimator: require './periodic_persistant_animator'
  PersistantAnimator:         require './persistant_animator'         