# generated by Neptune Namespaces v1.x.x
# file: art/engine/animation/namespace.coffee

Engine = require '../namespace'
module.exports = Engine.Animation ||
Engine.addNamespace 'Animation', class Animation extends Neptune.Base
  ;