# generated by Neptune Namespaces v0.1.0
# file: art/engine/animation/namespace.coffee

Engine = require '../namespace'
module.exports = Engine.Animation ||
Engine.addNamespace class Animation extends Neptune.Base
  ;