# generated by Neptune Namespaces v1.x.x
# file: art/engine/layout/namespace.coffee

Engine = require '../namespace'
module.exports = Engine.Layout ||
Engine.addNamespace 'Layout', class Layout extends Neptune.Base
  ;