# generated by Neptune Namespaces
# file: art/engine/layout/namespace.coffee

Engine = require '../namespace'
module.exports = Engine.Layout ||
Engine.addNamespace class Layout extends Neptune.Base
  ;