# generated by Neptune Namespaces
# file: art/engine/layout/namespace.coffee

Engine = require '../namespace'
module.exports = Engine.Layout ||
class Engine.Layout extends Neptune.Base
  @namespace: Engine
  @namespacePath: "Neptune.Art.Engine.Layout"

Engine.addNamespace Engine.Layout