// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Engine/Core/Layout/Functional/index.js

(module.exports = require('./namespace'))

.addModules({
  Basics:           require('./Basics'),
  ChildrenRelative: require('./ChildrenRelative'),
  ChildrenSize:     require('./ChildrenSize'),
  Padding:          require('./Padding'),
  Scale:            require('./Scale')
});