// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Engine/Core/Layout/Functional/namespace.js

module.exports = require('../namespace').addNamespace(
  'Functional',
  class Functional extends Neptune.PackageNamespace {}
);
