// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Engine/File/namespace.js

module.exports = require('../namespace').addNamespace(
  'File',
  class File extends Neptune.PackageNamespace {}
);
