// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Engine/Elements/ShapeChildren/index.js

(module.exports = require('./namespace'))

.addModules({
  OutlineElement: require('./OutlineElement')
});