# generated by Neptune Namespaces v3.x.x
# file: tests/Art.Engine/Elements/ShapeChildren/namespace.coffee

module.exports = (require '../namespace').addNamespace('ShapeChildren', class ShapeChildren extends Neptune.PackageNamespace)
