// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Engine/Elements/ShapeChildren/namespace.js

module.exports = require('../namespace').addNamespace(
  'ShapeChildren',
  class ShapeChildren extends Neptune.PackageNamespace {}
);
