# generated by Neptune Namespaces v1.x.x
# file: tests/Art/Engine/Events/index.coffee

module.exports = require './namespace'
.addModules
  PointerEvent:        require './PointerEvent'       
  PointerEventManager: require './PointerEventManager'