# generated by Neptune Namespaces v0.5
# file: tests/art/engine/events/index.coffee

module.exports = require './namespace'
.addModules
  PointerEventManager: require './pointer_event_manager'
  PointerEvent:        require './pointer_event'        