# generated by Neptune Namespaces v3.x.x
# file: tests/Art/Engine/Events/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  PointerEvent:        require './PointerEvent'       
  PointerEventManager: require './PointerEventManager'