# generated by Neptune Namespaces v0.4.1
# file: tests/art/engine/events/index.coffee

(module.exports = require './namespace')
.addModules
  PointerEvent:        require './pointer_event'
  PointerEventManager: require './pointer_event_manager'