# generated by Neptune Namespaces v1.x.x
# file: tests/Art/Engine/Events/namespace.coffee

Engine = require '../namespace'
module.exports = Engine.Events ||
Engine.addNamespace 'Events', class Events extends Neptune.Base
  ;