# generated by Neptune Namespaces v0.1.0
# file: tests/art/engine/events/namespace.coffee

Engine = require '../namespace'
module.exports = Engine.Events ||
Engine.addNamespace class Events extends Neptune.Base
  ;