# generated by Neptune Namespaces
# file: tests/art/engine/events/namespace.coffee

Engine = require '../namespace'
module.exports = Engine.Events ||
class Engine.Events extends Neptune.Base
  @namespace: Engine
  @namespacePath: "Neptune.Tests.Art.Engine.Events"

Engine.addNamespace Engine.Events