# generated by Neptune Namespaces v0.1.0
# file: art/engine/forms/index.coffee

(module.exports = require './namespace')
.addModules
  SynchronizedDomOverlay: require './synchronized_dom_overlay'
  TextInput:              require './text_input'