# generated by Neptune Namespaces
# file: src/art/engine/forms/namespace.coffee

Engine = require '../namespace'
module.exports = Engine.Forms ||
class Engine.Forms extends Neptune.Base
  @namespace: Engine
  @namespacePath: "Neptune.Art.Engine.Forms"

Engine.addNamespace Engine.Forms