# generated by Neptune Namespaces v0.3.0
# file: art/engine/forms/namespace.coffee

Engine = require '../namespace'
module.exports = Engine.Forms ||
Engine.addNamespace 'Forms', class Forms extends Neptune.Base
  ;