# generated by Neptune Namespaces v3.x.x
# file: Art/Engine/Elements/ShapeChildren/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  FillElement:    require './FillElement'   
  OutlineElement: require './OutlineElement'