# generated by Neptune Namespaces v1.x.x
# file: Art/Engine/Elements/ShapeChildren/index.coffee

module.exports = require './namespace'
.addModules
  FillElement:    require './FillElement'   
  OutlineElement: require './OutlineElement'