// generated by Neptune Namespaces v4.x.x
// file: Art/Engine/Elements/ShapeChildren/index.js

(module.exports = require('./namespace'))

.addModules({
  FillElement:    require('./FillElement'),
  OutlineElement: require('./OutlineElement')
});