# generated by Neptune Namespaces v3.x.x
# file: Art/Engine/Elements/ShapeChildren/namespace.coffee

module.exports = (require '../namespace').addNamespace('ShapeChildren', class ShapeChildren extends Neptune.PackageNamespace)
