# generated by Neptune Namespaces v2.x.x
# file: Art/Engine/Elements/ShapeChildren/namespace.coffee

Elements = require '../namespace'
module.exports = Elements.ShapeChildren ||
Elements.addNamespace 'ShapeChildren', class ShapeChildren extends Neptune.Base
  ;
