// generated by Neptune Namespaces v4.x.x
// file: Art/Engine/DevTools/index.js

(module.exports = require('./namespace'))

.addModules({
  GlobalEpochStat:       require('./GlobalEpochStat'),
  GlobalEpochStats:      require('./GlobalEpochStats'),
  GlobalEpochStatsStyle: require('./GlobalEpochStatsStyle')
});