# generated by Neptune Namespaces v2.x.x
# file: Art/Engine/DevTools/namespace.coffee

Engine = require '../namespace'
module.exports = Engine.DevTools ||
Engine.addNamespace 'DevTools', class DevTools extends Neptune.Base
  ;
