// generated by Neptune Namespaces v4.x.x
// file: Art/Engine/DevTools/namespace.js

module.exports = require('../namespace').addNamespace(
  'DevTools',
  class DevTools extends Neptune.PackageNamespace {}
);
