# generated by Neptune Namespaces v3.x.x
# file: Art/Engine/DevTools/namespace.coffee

module.exports = (require '../namespace').addNamespace('DevTools', class DevTools extends Neptune.PackageNamespace)
